name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PORT: ${{ secrets.PORT }}
  MESSAGE: ${{ secrets.MESSAGE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create .env file from GitHub Secrets
      run: |
        echo "PORT=${PORT}" >> .env
        echo "MESSAGE=${MESSAGE}" >> .env

    - name: Run tests
      run: npm test
